* <2021-05-23 Sun>
You find yourself in the world of mirage.
There's boundless ocean of lava.
In the gaps between the clouds you see a little bit of the surface - a boundless ocean of lava.
Layer of coouds and vapors.
The atmosphere here is pretty unusual for a piraty tavern - not rowdy and rambinxious, but subdued, tense. Everyone knows what's coming - the Empire. There's a huge warship filled with paladins, here to reinstate the rules of law.
Not defeated, Mont Blanc is fighting it! Amazing.
Boom! And the mayor guy runs jn, panicking.
See? I bet I can do this!


Gramatical - Hayward Alabaster. Freelance, goes wehre the wind takes him, looking.
Jordan - Roguish pirate, swindling, gabling, tax evasion.
Nero - Doing my thing,
CAstial - cleric, follower of the waters way down below. water magic, healer.

get into nobles

rowboat

pirates fighting over the last rowboat.

even - critical failure
odd - cri

3 pirates

jordan barrel

players want to rescue pirates.

puke it out if you want.

tiny shrim

jordan is separate.

mist it up.

he means business.

paint me a word picture.

did you guys have fun?
any feedback?

have a mother
i will not get it together, I wanna go home to mommy.

you're the best aroun

he's about to scream, like a little girl.

jordan and red - in armor.
nero is last.

they just no dat you.

pirate attracts attention.
justify it in fiction.

paladins know that the door is opened.

hayward accidentally shot one of the pirates.
another eyepatch.

dynamite

paladins run to sound the alarm.

how do you approach this.

joseph no, you were the best of us.

he's gor the right

mateys, take this mother down.

pirates stampede up the staiers

make the ship do a barrel roll.

Viva Morrow

i was born for this weapon.

flying pegasi.

it will go down in piraty legends for centruies.


before eventually dying from scurvy.
gamble the ship away.

everyone saw the true face of god.
waterfalls off of the islands.
